apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "smartflows.labels" . | nindent 4 }}
  name: blob-storage-secret
  {{ if .Values.createNamespace }}
  namespace: {{ include "smartflows.namespace" . }}
  {{ end }} 
type: Opaque
data:
  accountName: {{ .Values.blobStorage.accountName | b64enc }}
  accountKey: {{ .Values.blobStorage.accountKey | b64enc }}
  containerName: {{ .Values.blobStorage.containerName | b64enc }}