{{- if eq .Values.multitenant "true" }}
apiVersion: v1
data:
  PROJECT_MULTITENANT_ADMIN_PASWORDHASH: "$2a$12$ykizUu2gDg2FyqDxdW62KOX8A9WIsptC5Jnm8nMFt5MmtdeCca0IC"
  PROJECT_MULTITENANT_DOMAIN_USER: "tenantAdmin"
kind: ConfigMap
metadata:
  name: configmap-multitenant
  {{ if eq .Values.createNamespace "true" }}
  namespace: {{ .Values.namespace }}
  {{ end }}
{{- end }}