apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "smartflows.labels" . | nindent 4 }}
  name: smartflows
  {{ if .Values.createNamespace }}
  namespace: {{ include "smartflows.namespace" . }}
  {{ end }}
spec:
  type: {{ .Values.smartflows.service.type }}
  ports:
    - name: http
      port: {{ .Values.smartflows.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "smartflows.selectorLabels" . | nindent 4 }}
