{{- if eq .Values.sqlServer.server "sqlserver" }}
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: sqlserver
  name: sqlserver
  {{ if .Values.createNamespace }}
  namespace: {{ include "smartflows.namespace" . }}
  {{ end }}
spec:
  ports:
    - name: "1433"
      port: 1433
      targetPort: 1433
  selector:
    io.kompose.service: sqlserver
status:
  loadBalancer: {}
{{- end }}