{{- if eq .Values.sqlServer.server "sqlserver" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: sqlserver-claim0
  name: sqlserver-claim0
  {{ if .Values.createNamespace }}
  namespace: {{ include "smartflows.namespace" . }}
  {{ end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
{{- end }}