{{- if eq .Values.sqlServer.server "sqlserver" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: sqlserver
  name: sqlserver
  {{ if .Values.createNamespace }}
  namespace: {{ include "smartflows.namespace" . }}
  {{ end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sqlserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: sqlserver
    spec:
      containers:
        - env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: {{ .Values.sqlServer.password }}
          image: mcr.microsoft.com/mssql/server:2022-latest
          livenessProbe:
            exec:
              command:
                - /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$SA_PASSWORD" -Q "select 1"
          name: sqlserver
          ports:
            - containerPort: 1433
          resources: {}
          volumeMounts:
            - mountPath: /var/opt/mssql
              name: sqlserver-claim0
      restartPolicy: Always
      securityContext:
        fsGroup: 10001
      volumes:
        - name: sqlserver-claim0
          persistentVolumeClaim:
            claimName: sqlserver-claim0
status: {}
{{- end }}