{{- if eq .Values.distributed "true" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: redis
  name: redis
  {{ if eq .Values.createNamespace "true" }}
  namespace: {{ .Values.namespace }}
  {{ end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
        - image: "{{ .Values.redis.image }}"
          name: redis
          ports:
            - name: redis
              containerPort: 6379
            - name: rediss
              containerPort: 6380
            - name: http-ui
              containerPort: 8001
      restartPolicy: Always
{{- end }}