apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "smartflows.labels" . | nindent 4 }}
  name: regcred
  {{ if .Values.createNamespace }}
  namespace: {{ include "smartflows.namespace" . }}
  {{ end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}