apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "smartflows.labels" . | nindent 4 }}
  name: smartflows
  {{ if .Values.createNamespace }}
  namespace: {{ include "smartflows.namespace" . }}
  {{ end }}
spec:
  replicas: {{ .Values.smartflows.replicaCount }}
  selector:
    matchLabels:
      {{- include "smartflows.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "smartflows.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - env:
            {{- include "createEnvVars" .Values.smartflows.settings | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          name: smartflows
          ports:
            - name: http
              containerPort: {{ .Values.smartflows.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
